// src/screens/IncidentDetailScreen.js
// Full-detail view for a single Evidence Vault incident record
import { useState } from "react";
import {
  View, Text, StyleSheet, ScrollView, TouchableOpacity,
  Share, Alert, Image, ActivityIndicator
} from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { Ionicons } from "@expo/vector-icons";
import { useNavigation, useRoute } from "@react-navigation/native";
import { supabase } from "../api/supabase";
import { BG, CARD, BORDER, PRIMARY, PINK, TEXT, SUBTEXT, SUCCESS, DANGER, WARNING } from "../theme/colors";

// Optional PDF export
let Print = null, Sharing = null;
try { Print = require("expo-print"); } catch (_) {}
try { Sharing = require("expo-sharing"); } catch (_) {}

const TYPE_COLORS = {
  "Verbal Harassment":   { color: "#f87171", icon: "megaphone",        bg: "rgba(248,113,113,0.1)"  },
  "Physical Harassment": { color: "#ef4444", icon: "hand-right",       bg: "rgba(239,68,68,0.1)"    },
  "Stalking":            { color: "#fb923c", icon: "eye",              bg: "rgba(251,146,60,0.1)"   },
  "Online Harassment":   { color: "#a78bfa", icon: "phone-portrait",   bg: "rgba(167,139,250,0.1)"  },
  "Eve Teasing":         { color: "#f472b6", icon: "alert-circle",     bg: "rgba(244,114,182,0.1)"  },
  "Other":               { color: "#94a3b8", icon: "document-text",    bg: "rgba(148,163,184,0.1)"  },
};

export default function IncidentDetailScreen() {
  const insets     = useSafeAreaInsets();
  const navigation = useNavigation();
  const route      = useRoute();
  const incident   = route.params?.incident;

  const [deleting, setDeleting]   = useState(false);
  const [exporting, setExporting] = useState(false);

  if (!incident) {
    return (
      <View style={[s.root, { alignItems: "center", justifyContent: "center" }]}>
        <ActivityIndicator color={PRIMARY} size="large" />
      </View>
    );
  }

  const meta = TYPE_COLORS[incident.type] || TYPE_COLORS["Other"];

  const formatDate = (iso) => {
    try {
      return new Date(iso).toLocaleDateString("en-IN", {
        weekday: "long", day: "numeric", month: "long", year: "numeric"
      });
    } catch { return iso; }
  };

  const formatTime = (iso) => {
    try {
      return new Date(iso).toLocaleTimeString("en-IN", {
        hour: "2-digit", minute: "2-digit", hour12: true
      });
    } catch { return ""; }
  };

  // ── Share complaint text ──────────────────────────────────────────────────
  const shareComplaint = async () => {
    if (!incident.complaint) {
      Alert.alert("No Complaint", "Generate an AI complaint draft first from the Vault.");
      return;
    }
    try {
      await Share.share({
        title: `ShieldHer — ${incident.type} Complaint`,
        message: incident.complaint,
      });
    } catch (e) {
      console.error("Share error:", e);
    }
  };

  // ── Export as PDF ─────────────────────────────────────────────────────────
  const exportPDF = async () => {
    if (!Print || !Sharing) {
      Alert.alert("Not Available", "Install expo-print and expo-sharing to enable PDF export.");
      return;
    }
    if (!incident.complaint) {
      Alert.alert("No Complaint", "Generate an AI complaint draft first.");
      return;
    }
    setExporting(true);
    try {
      const html = `
        <!DOCTYPE html><html>
        <head><meta charset="utf-8"/>
        <style>
          body { font-family: Georgia, serif; max-width: 720px; margin: 40px auto; color: #1a1a1a; }
          h1 { color: #7c3aed; font-size: 22px; border-bottom: 2px solid #7c3aed; padding-bottom: 10px; }
          .meta { background: #f5f3ff; padding: 14px; border-radius: 8px; margin: 20px 0; font-size: 13px; }
          .label { font-weight: bold; color: #6d28d9; }
          .complaint { white-space: pre-wrap; line-height: 1.8; font-size: 14px; }
          .footer { margin-top: 40px; font-size: 11px; color: #9ca3af; border-top: 1px solid #e5e7eb; padding-top: 12px; }
        </style></head>
        <body>
          <h1>ShieldHer — Evidence Record</h1>
          <div class="meta">
            <p><span class="label">Incident Type:</span> ${incident.type}</p>
            <p><span class="label">Date:</span> ${formatDate(incident.created_at)}</p>
            <p><span class="label">Time:</span> ${formatTime(incident.created_at)}</p>
            ${incident.location ? `<p><span class="label">Location:</span> ${incident.location}</p>` : ""}
          </div>
          ${incident.description ? `<p><strong>Description:</strong><br/>${incident.description}</p>` : ""}
          ${incident.complaint ? `<hr/><h2>Complaint Draft</h2><div class="complaint">${incident.complaint}</div>` : ""}
          <div class="footer">Generated by ShieldHer — ${new Date().toLocaleString("en-IN")}</div>
        </body></html>
      `;
      const { uri } = await Print.printToFileAsync({ html, base64: false });
      await Sharing.shareAsync(uri, {
        mimeType: "application/pdf",
        dialogTitle: "Share Incident Report",
        UTI: "com.adobe.pdf",
      });
    } catch (e) {
      Alert.alert("Export Failed", e.message || "Could not generate PDF.");
    }
    setExporting(false);
  };

  // ── Delete incident ───────────────────────────────────────────────────────
  const deleteIncident = () => {
    Alert.alert(
      "Delete Record",
      "This will permanently remove this incident record from your vault. This cannot be undone.",
      [
        { text: "Cancel", style: "cancel" },
        {
          text: "Delete",
          style: "destructive",
          onPress: async () => {
            setDeleting(true);
            try {
              await supabase.from("incidents").delete().eq("id", incident.id);
              navigation.goBack();
            } catch (e) {
              Alert.alert("Error", "Could not delete the record.");
            }
            setDeleting(false);
          },
        },
      ]
    );
  };

  return (
    <View style={[s.root, { paddingTop: insets.top }]}>
      {/* ── Custom Header ─────────────────────────────────────────────── */}
      <View style={s.header}>
        <TouchableOpacity style={s.backBtn} onPress={() => navigation.goBack()}>
          <Ionicons name="arrow-back" size={20} color={TEXT} />
        </TouchableOpacity>
        <Text style={s.headerTitle}>Incident Detail</Text>
        <TouchableOpacity style={s.deleteBtn} onPress={deleteIncident} disabled={deleting}>
          {deleting
            ? <ActivityIndicator color={DANGER} size="small" />
            : <Ionicons name="trash-outline" size={20} color={DANGER} />}
        </TouchableOpacity>
      </View>

      <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={s.content}>

        {/* ── Hero card ───────────────────────────────────────────────── */}
        <View style={[s.heroCard, { borderColor: meta.color + "40", backgroundColor: meta.bg }]}>
          <View style={[s.typeIconWrap, { backgroundColor: meta.color + "20" }]}>
            <Ionicons name={meta.icon} size={28} color={meta.color} />
          </View>
          <Text style={[s.heroType, { color: meta.color }]}>{incident.type}</Text>
          <Text style={s.heroDate}>{formatDate(incident.created_at)}</Text>
          <Text style={s.heroTime}>{formatTime(incident.created_at)}</Text>
        </View>

        {/* ── Evidence image ──────────────────────────────────────────── */}
        {incident.media_url ? (
          <View style={s.mediaCard}>
            <View style={s.mediaHeader}>
              <Ionicons name="image" size={14} color={PRIMARY} />
              <Text style={s.sectionLabel}>EVIDENCE</Text>
            </View>
            <Image
              source={{ uri: incident.media_url }}
              style={s.evidenceImage}
              resizeMode="cover"
            />
            <View style={s.encBadge}>
              <Ionicons name="lock-closed" size={10} color={SUCCESS} />
              <Text style={s.encBadgeText}>Encrypted · Stored Securely</Text>
            </View>
          </View>
        ) : null}

        {/* ── Metadata ────────────────────────────────────────────────── */}
        <View style={s.metaCard}>
          <Text style={s.sectionLabel}>INCIDENT DETAILS</Text>

          {incident.location ? (
            <View style={s.metaRow}>
              <Ionicons name="location-outline" size={16} color={PRIMARY} />
              <View style={s.metaTextWrap}>
                <Text style={s.metaLabel}>Location</Text>
                <Text style={s.metaValue}>{incident.location}</Text>
              </View>
            </View>
          ) : null}

          {incident.description ? (
            <View style={[s.metaRow, { alignItems: "flex-start" }]}>
              <Ionicons name="document-text-outline" size={16} color={PRIMARY} style={{ marginTop: 2 }} />
              <View style={s.metaTextWrap}>
                <Text style={s.metaLabel}>Description</Text>
                <Text style={s.metaValue}>{incident.description}</Text>
              </View>
            </View>
          ) : null}

          <View style={s.metaRow}>
            <Ionicons name="calendar-outline" size={16} color={PRIMARY} />
            <View style={s.metaTextWrap}>
              <Text style={s.metaLabel}>Recorded On</Text>
              <Text style={s.metaValue}>{formatDate(incident.created_at)} at {formatTime(incident.created_at)}</Text>
            </View>
          </View>
        </View>

        {/* ── AI Complaint ─────────────────────────────────────────────── */}
        {incident.complaint ? (
          <View style={s.complaintCard}>
            <View style={s.complaintHeader}>
              <View style={s.complaintIconBg}>
                <Ionicons name="sparkles" size={14} color={SUCCESS} />
              </View>
              <Text style={s.complaintTitle}>AI-Drafted Complaint</Text>
              <View style={s.aiBadge}>
                <Text style={s.aiBadgeText}>Gemini</Text>
              </View>
            </View>
            <ScrollView
              style={s.complaintScroll}
              nestedScrollEnabled
              showsVerticalScrollIndicator={false}
            >
              <Text style={s.complaintText}>{incident.complaint}</Text>
            </ScrollView>

            {/* Action row */}
            <View style={s.actionRow}>
              <TouchableOpacity style={[s.actionBtn, { borderColor: PRIMARY + "40" }]} onPress={shareComplaint}>
                <Ionicons name="share-outline" size={16} color={PRIMARY} />
                <Text style={[s.actionBtnText, { color: PRIMARY }]}>Share</Text>
              </TouchableOpacity>

              <TouchableOpacity
                style={[s.actionBtn, { borderColor: SUCCESS + "40", flex: 2 }]}
                onPress={exportPDF}
                disabled={exporting}
              >
                {exporting
                  ? <ActivityIndicator color={SUCCESS} size="small" />
                  : <>
                      <Ionicons name="document" size={16} color={SUCCESS} />
                      <Text style={[s.actionBtnText, { color: SUCCESS }]}>Export PDF</Text>
                    </>}
              </TouchableOpacity>
            </View>
          </View>
        ) : (
          <View style={[s.complaintCard, { alignItems: "center", gap: 8 }]}>
            <Ionicons name="document-text-outline" size={28} color={SUBTEXT} />
            <Text style={[s.metaLabel, { textAlign: "center" }]}>No complaint draft yet</Text>
            <Text style={[s.metaValue, { textAlign: "center", opacity: 0.6 }]}>
              Open the Vault, select this record, and tap "Generate AI Complaint" to create a formal FIR draft.
            </Text>
          </View>
        )}

        <View style={{ height: 40 }} />
      </ScrollView>
    </View>
  );
}

const s = StyleSheet.create({
  root:             { flex: 1, backgroundColor: BG },

  // Header
  header:           { flexDirection: "row", alignItems: "center", paddingHorizontal: 16, paddingVertical: 14, borderBottomWidth: 1, borderBottomColor: BORDER },
  backBtn:          { width: 38, height: 38, borderRadius: 12, backgroundColor: CARD, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: BORDER },
  headerTitle:      { flex: 1, fontSize: 17, fontWeight: "700", color: TEXT, textAlign: "center" },
  deleteBtn:        { width: 38, height: 38, borderRadius: 12, backgroundColor: "rgba(239,68,68,0.1)", alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: "rgba(239,68,68,0.25)" },

  content:          { padding: 16, gap: 14 },

  // Hero
  heroCard:         { borderRadius: 20, borderWidth: 1, padding: 24, alignItems: "center", gap: 8 },
  typeIconWrap:     { width: 64, height: 64, borderRadius: 20, alignItems: "center", justifyContent: "center", marginBottom: 4 },
  heroType:         { fontSize: 20, fontWeight: "800" },
  heroDate:         { fontSize: 15, color: TEXT, fontWeight: "500" },
  heroTime:         { fontSize: 13, color: SUBTEXT },

  // Media
  mediaCard:        { backgroundColor: CARD, borderRadius: 20, padding: 16, borderWidth: 1, borderColor: BORDER, gap: 12 },
  mediaHeader:      { flexDirection: "row", alignItems: "center", gap: 6 },
  evidenceImage:    { width: "100%", height: 200, borderRadius: 14, backgroundColor: "#1a1130" },
  encBadge:         { flexDirection: "row", alignItems: "center", gap: 5, backgroundColor: "rgba(34,197,94,0.08)", borderRadius: 10, paddingHorizontal: 10, paddingVertical: 5, alignSelf: "flex-start", borderWidth: 1, borderColor: "rgba(34,197,94,0.2)" },
  encBadgeText:     { fontSize: 10, color: SUCCESS, fontWeight: "700" },

  // Meta
  metaCard:         { backgroundColor: CARD, borderRadius: 20, padding: 18, borderWidth: 1, borderColor: BORDER, gap: 16 },
  sectionLabel:     { fontSize: 10, color: SUBTEXT, fontWeight: "700", letterSpacing: 1.2, textTransform: "uppercase" },
  metaRow:          { flexDirection: "row", alignItems: "center", gap: 12 },
  metaTextWrap:     { flex: 1, gap: 2 },
  metaLabel:        { fontSize: 11, color: SUBTEXT, fontWeight: "600" },
  metaValue:        { fontSize: 14, color: TEXT, lineHeight: 20 },

  // Complaint
  complaintCard:    { backgroundColor: CARD, borderRadius: 20, padding: 18, borderWidth: 1, borderColor: "rgba(34,197,94,0.2)", gap: 12 },
  complaintHeader:  { flexDirection: "row", alignItems: "center", gap: 8 },
  complaintIconBg:  { width: 30, height: 30, borderRadius: 9, backgroundColor: "rgba(34,197,94,0.12)", alignItems: "center", justifyContent: "center" },
  complaintTitle:   { fontSize: 14, fontWeight: "700", color: SUCCESS, flex: 1 },
  aiBadge:          { backgroundColor: "rgba(139,92,246,0.12)", borderRadius: 8, paddingHorizontal: 8, paddingVertical: 3, borderWidth: 1, borderColor: "rgba(139,92,246,0.25)" },
  aiBadgeText:      { fontSize: 10, color: PRIMARY, fontWeight: "700" },
  complaintScroll:  { maxHeight: 220, backgroundColor: "rgba(255,255,255,0.03)", borderRadius: 12, padding: 12, borderWidth: 1, borderColor: BORDER },
  complaintText:    { fontSize: 13, color: SUBTEXT, lineHeight: 21 },

  // Actions
  actionRow:        { flexDirection: "row", gap: 10 },
  actionBtn:        { flex: 1, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 6, borderWidth: 1, borderRadius: 14, paddingVertical: 12 },
  actionBtnText:    { fontWeight: "700", fontSize: 13 },
});
